[tool.poetry]
name = "waterquality"
version = "0.1.0"
description = ""
authors = ["Luis Angel Rodriguez Reiners <luis.reiners@unical.it>"]
readme = "README.md"

[tool.poetry.scripts]
waterquality = "waterquality.main:app"

[tool.poetry.dependencies]
python = "^3.11"
typer = "^0.12.5"
pandas = "^2.2.3"
matplotlib = "^3.9.2"
keras-tuner = "^1.4.7"
scikit-learn = "^1.5.2"
tensorflow = "^2.17.0"
plotly = "^5.24.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
